# Generated by Django 5.2.3 on 2025-10-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
